feat: add new input variable to disable local authentication by default
equinor/terraform-azurerm-app-insights pull request #43
Opened 2024-05-10 07:41 UTC by chbul

Parent issue: equinor/terraform-baseline#144

2024-05-10 07:58 UTC, hknutsen commented
@equinor/terraform-baseline-maintainers This would require developers to update their applications to use Entra ID authentication for sending metrics to Application Insights ([docs](https://learn.microsoft.com/en-us/azure/azure-monitor/app/azure-ad-authentication?tabs=net)). Should we consider this a breaking change?

2024-05-10 08:20 UTC, chbul commented
> @equinor/terraform-baseline-maintainers This would require developers to update their applications to use Entra ID authentication for sending metrics to Application Insights ([docs](https://learn.microsoft.com/en-us/azure/azure-monitor/app/azure-ad-authentication?tabs=net)). Should we consider this a breaking change?

According to [this](https://musical-fortnight-fda05d3c.pages.github.io/#git-commit-message-guidelines), BREAKING CHANGE is mandatory for non-backwards compatible changes.

2024-05-10 08:45 UTC, hknutsen requested changes
See suggestion 🙂

2024-05-10 08:45 UTC, hknutsen commented on variables.tf
> +  description = "Disable local authentication to enable RBAC."
Boolean variables are often phrased as questions. Also, could be useful to specify what the difference is between having this disabled or enabled:

```suggestion
  description = "Should local authentication be disabled for this Application Insights component? If true, the \"Monitoring Metrics Publisher\" role is required for Microsoft Entra authentication."
```

2024-05-13 11:52 UTC, hknutsen approved these changes

2024-05-13 12:16 UTC, hknutsen commented
@chbul Feel free to squash and merge 🚀

2024-05-13 12:18 UTC, merged